/* 金铲铲阵容合集 · 数据文件
 * 由 AI 根据飞书文档生成，请勿手动修改格式。
 * 更新方式：将新版 data.js 覆盖上传到 GitHub 仓库（JCCwenjiang/lineup-data）即可，粉丝端自动更新。 */
window.LINEUP_DATA=[{"n": "S18月男豹女2.0", "ver": "V18.2a", "tier": "T0+", "cat": "cur", "isRec": true, "note": "目前版本特别适合偷分的一套阵容", "code": "#S18月男豹女2.0（蚊酱）#MjE5OTkwMzU4Nzg0MzIzNzkxNzkwMDQ2MzY2MjU0"},
  {"n": "地狱火希维尔", "ver": "V18.2", "tier": "T0", "cat": "cur", "isRec": true, "note": "有转必玩，当前版本最强转职体系阵容", "code": "#蚊酱S18「地狱火希维尔」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg5Mjc4NjIzNDMx"},
  {"n": "S18日蚀妖姬2.0", "ver": "V18.2a", "tier": "T0-", "cat": "cur", "note": "独家赌狗天花板，高分段把把有分", "code": "#S18日蚀妖姬2.0（蚊酱）#MjE5OTkwMzU4Nzg0MzIzNzkxNzkwMDQ5MzE3NzM5"},
  {"n": "迫击炮5神谕大嘴", "ver": "V18.2a", "tier": "T0-", "cat": "cur", "note": "同行多不建议玩，体系牌来的慢难吃分", "code": "#迫击炮5神谕大嘴（蚊酱）#MjE5OTEzMzc4ODgxMDY5MTMxNzg5NzAxOTUyMTc0"},
  {"n": "主宰Flex", "ver": "V18.2", "tier": "T0-", "cat": "cur", "note": "目前最强主宰体系牌，同行多不建议玩", "code": "#主宰Flex（蚊酱）#MjE5OTkwMzU4Nzg0MzIzNzkxNzg5NTU0MDQzNjgx"},
  {"n": "终身黄铜巨龙", "ver": "V18.2", "tier": "T0", "cat": "cur", "note": "终身黄铜叠加23%增伤", "code": "#黄铜巨龙（蚊酱）#MjE5OTkwMzU4Nzg0MzIzNzkxNzg5NDQ4MzQ5NzI2"},
  {"n": "443希维尔", "ver": "V18.2", "tier": "T0", "cat": "cur", "note": "最公式玩法，无脑上分必选", "code": "#443希维尔（蚊酱）#MjE5OTkwMzU4Nzg0MzIzNzkxNzg5NDUzOTE4MDU1"},
  {"n": "寒冰巨龙95", "ver": "V18.2", "tier": "T0", "cat": "cur", "note": "当前版本最无脑95玩法", "code": "#S18寒冰巨龙95（蚊酱）#MjE5OTkwMzU4Nzg0MzIzNzkxNzg5Mzc5OTk0NDg4"},
  {"n": "野怪蛙妃", "ver": "V18.2", "tier": "T1", "cat": "cur", "note": "7野怪最新吃分玩法", "code": "#蚊酱S18「野怪蛙妃」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg5Mjg1MjA3NjQ5"},
  {"n": "S18月男豹女", "ver": "V18.2", "tier": "T0-", "cat": "cur", "note": "拼多多月男，8人口启动", "code": "#S18月男豹女（蚊酱）#MjE5OTkwMzU4Nzg0MzIzNzkxNzg5MzczOTQ0NjQz"},
  {"n": "拉露恩95", "ver": "V18.2", "tier": "T0", "cat": "cur", "note": "赌狗必玩，版本更新后最强95阵容", "code": "#蚊酱S18「拉露恩95」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg5MTE1NzEwNjc3"},
  {"n": "闭环妖姬", "ver": "V18.2", "tier": "T0", "cat": "cur", "note": "无限复制友军，后期更容易追3星4费", "code": "#蚊酱S18「闭环妖姬」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg5MDMzNDg4NjUx"},
  {"n": "日蚀阿卡丽", "ver": "V18.2", "tier": "T1", "cat": "cur", "note": "简码，晚点上详细思路", "code": "#蚊酱S18「日蚀阿卡丽」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg5MDIzMDY3MDU2"},
  {"n": "重装永恒95", "ver": "V18.2", "tier": "T0", "cat": "cur", "note": "简码，晚点上详细思路", "code": "#蚊酱S18「重装永恒95」#MTA5OTk1MjMwNzcxNjIzNTQxNzg5MDEyODk3MDQz"},
  {"n": "S18黑暗仪式蜘蛛", "ver": "V18.2a", "tier": "T0+", "cat": "hex", "isRec": true, "note": "海克斯专属阵容，没有别硬玩", "code": "#S18黑暗仪式蜘蛛（蚊酱）#MjE5OTkwMzU4Nzg0MzIzNzkxNzkwMjM5MDk1NDU3"},
  {"n": "好事成双蛇女", "ver": "V18.1", "tier": "S", "cat": "hex", "note": "海克斯专属", "code": "#蚊酱S18「好事成双蛇女」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3NDU3MTU3NjY3"},
  {"n": "世纪和解", "ver": "V18.1", "tier": "S", "cat": "hex", "note": "海克斯专属", "code": "#蚊酱S18海克斯专属「世纪和解」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3MjE5MDM2MDcz"},
  {"n": "S18裁决沙皇", "publishedAt": "2026-09-26T08:00:02.810Z", "ver": "V18.2a", "tier": "T1", "cat": "cur", "isRec": false, "tags": ["娱乐"], "note": "开局给沙皇/螳螂再玩，强度一般，娱乐一下", "code": "#S18裁决沙皇（蚊酱）#MjE5OTkwMzU4Nzg0MzIzNzkxNzkwNDAzNDA1NzM1"},
  {"n": "顺流而下-6级3星5费", "ver": "V18.1c", "tier": "已禁用", "cat": "hist", "banned": true, "note": "最新版本已经不能玩了", "code": "#蚊酱S18「顺流而下-6级3星5费」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg4ODYwNTQwNDE3"},
  {"n": "地狱火寒冰", "ver": "V18.1c", "tier": "T0+", "cat": "hist", "note": "刚需地狱火转职纹章", "code": "#蚊酱S18「地狱火寒冰」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg4NzcxOTI2NDE0"},
  {"n": "主宰颗秒女警", "ver": "V18.1c", "tier": "T0-", "cat": "hist", "isRec": true, "note": "强势2费阵容", "code": "#蚊酱S18「主宰颗秒女警」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg4NzY0MjY0Mzc0"},
  {"n": "剑圣狮子狗", "ver": "V18.1c", "tier": "T1", "cat": "hist", "note": "打钱流狮子狗", "code": "#蚊酱S18「剑圣狮子狗」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg4NjA3NjA0NTY4"},
  {"n": "重装皎月2.0", "ver": "V18.1c", "tier": "T0+", "cat": "hist", "isRec": true, "note": "最强皎月新玩法", "code": "#蚊酱S18「重装皎月2.0」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg4NTExODU3NzA0"},
  {"n": "大红和大蓝", "ver": "V18.1c", "tier": "T0", "cat": "hist", "isRec": true, "note": "适合把把硬玩", "code": "#大红和大蓝#MjE5OTkwMzU4Nzg0MzIzNzkxNzg4NDExNDA1NTM5"},
  {"n": "日蚀韦鲁斯", "ver": "V18.1b", "tier": "T0", "cat": "hist", "note": "适合把把硬玩", "code": "#蚊酱S18「日蚀韦鲁斯」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg4MzQ1MTE5NzYz"},
  {"n": "花仙子蜘蛛", "ver": "V18.1b", "tier": "T1+", "cat": "hist", "note": "有转必玩系列", "code": "#蚊酱S18「花仙子蜘蛛」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg4MjQ4NDU4MjU2"},
  {"n": "裁决婕拉", "ver": "V18.1b", "tier": "T0+", "cat": "hist", "note": "适合把把硬玩", "code": "#蚊酱S18「裁决婕拉」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg4MjYwNTM1MzE5"},
  {"n": "神谕莫甘娜", "ver": "V18.1b", "tier": "T0", "cat": "hist", "note": "冷门上分", "code": "#蚊酱S18「神谕莫甘娜」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg4MTc4NTQxMzQx"},
  {"n": "重装月男", "ver": "V18.1b", "tier": "T0+", "cat": "hist", "note": "最新84上分阵容", "code": "#蚊酱S18「重装月男」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg4MTY5ODk3MTU4"},
  {"n": "野怪小红小蓝", "ver": "V18.1b", "tier": "S+", "cat": "hist", "note": "1费赌狗", "code": "#蚊酱S18「野怪小红小蓝」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg4MDgzNTU1NjEy"},
  {"n": "螳螂蛇女2.0", "ver": "V18.1b", "tier": "S+", "cat": "hist", "note": "依然强势", "code": "#蚊酱S18「螳螂蛇女2.0」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3OTk2MDEzMzA2"},
  {"n": "永恒月男", "ver": "V18.1b", "tier": "S+", "cat": "hist", "note": "新晋84", "code": "#蚊酱S18「永恒月男」#MjE5OTEzMzc4ODgxMDY5MTMxNzg3OTExNjUxNTk3"},
  {"n": "日月双蚀", "ver": "V18.1b", "tier": "S+", "cat": "hist", "note": "强势上分", "code": "#蚊酱S18「日月双蚀」#MjE5OTEzMzc4ODgxMDY5MTMxNzg3ODQyOTc2Mjg0"},
  {"n": "护卫蛇女", "ver": "V18.1b", "tier": "S+", "cat": "hist", "note": "更新后强势3费", "code": "#蚊酱S18「护卫蛇女」#MjE5OTEzMzc4ODgxMDY5MTMxNzg3ODE0MzY4MTYy"},
  {"n": "峡谷巨龙", "ver": "V18.1b", "tier": "S", "cat": "hist", "note": "7巨龙95", "code": "#蚊酱S18「峡谷巨龙」#MjE5OTEzMzc4ODgxMDY5MTMxNzg3ODE0MzQyODA5"},
  {"n": "主宰月男", "ver": "V18.1b", "tier": "S", "cat": "hist", "note": "冷门偷分", "code": "#蚊酱S18「主宰月男」#MjE5OTEzMzc4ODgxMDY5MTMxNzg3ODE0MzA1MzI1"},
  {"n": "永恒莲华盗宗", "ver": "V18.1", "tier": "S+", "cat": "hist", "note": "新晋强势盗宗84", "code": "#蚊酱S18「永恒莲华盗宗」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3NzI4OTM1NDE3"},
  {"n": "万盾希维尔", "ver": "V18.1", "tier": "S+", "cat": "hist", "note": "献祭流轮子妈", "code": "#蚊酱S18「万盾希维尔」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3NzMzMjc1NTQw"},
  {"n": "重装猎人女警", "ver": "V18.1", "tier": "S", "cat": "hist", "note": "2费赌狗", "code": "#蚊酱S18「重装猎人女警」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3NDczMDY5NzYz"},
  {"n": "重装月蚀鸡哥", "ver": "V18.1", "tier": "SSS", "cat": "hist", "note": "当前最强3费", "code": "#蚊酱S18「重装鸡哥」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3MzkwODA0MDgz"},
  {"n": "443双狼", "ver": "V18.1", "tier": "S+", "cat": "hist", "note": "2费赌狗", "code": "#蚊酱S18「443双狼」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3MjE4NjA0MjU2"},
  {"n": "德莱文九五", "ver": "V18.1", "tier": "SS", "cat": "hist", "note": "最强95", "code": "#蚊酱S18「峡谷德莱文95」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3MTk0MTk3MjQ5"},
  {"n": "重装狮子狗", "ver": "V18.0", "tier": "S", "cat": "hist", "note": "3费赌狗", "code": "#蚊酱S18「重装狮子狗」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3MTgwNjI4NDUw"},
  {"n": "灵魂莲花阿狸", "ver": "V18.1", "tier": "S-", "cat": "hist", "note": "盗宗84", "code": "#蚊酱S18「7莲花阿狸」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3MTkxNTg3ODAy"},
  {"n": "裁决芸阿娜", "ver": "V18.1", "tier": "A+", "cat": "hist", "note": "2费赌狗", "code": "#蚊酱S18「裁决芸阿娜」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3MTgwMDk5OTM2"},
  {"n": "永恒天使霞", "ver": "V18.1", "tier": "S", "cat": "hist", "note": "1费赌狗", "code": "#蚊酱S18「永恒天使霞」#MjE5OTkwMzU4Nzg0MzIzNzkxNzg3MTgwMTI0OTQ0"},
  {"n": "基兰开局", "ver": "V18.2", "tier": "SSS", "cat": "s165", "note": "开局给基兰/奥恩", "code": "#蚊酱S16.5恭喜发财「基兰开局」#MTA5OTk1MjMwNzcxNjIzNTQxNzg5MDExMTY4NDEy"},
  {"n": "杰斯开局", "ver": "V18.2", "tier": "SSS", "cat": "s165", "note": "开局杰斯/卢娜", "code": "#蚊酱S16.5恭喜发财「杰斯开局」#MTA5OTk1MjMwNzcxNjIzNTQxNzg5MDExMzE1NDI3"},
  {"n": "千珏开局", "ver": "V18.2", "tier": "SS", "cat": "s165", "note": "开局千珏", "code": "#蚊酱S16.5恭喜发财（千珏开局）#MTA5OTk1MjMwNzcxNjIzNTQxNzg5MDExNDE0ODU5"},
  {"n": "龙女开局", "ver": "V18.2", "tier": "SS", "cat": "s165", "note": "开局龙女", "code": "#蚊酱S16.5恭喜发财「龙女开局」#MTA5OTk1MjMwNzcxNjIzNTQxNzg5MDExNjI0NjU5"},
  {"n": "稻草人开局", "ver": "V18.2", "tier": "SS", "cat": "s165", "note": "开局稻草人", "code": "#蚊酱S16.5恭喜发财「稻草人开局」#MTA5OTk1MjMwNzcxNjIzNTQxNzg5MDExNzAwNzA0"},
  {"n": "赛娜开局", "ver": "V18.2", "tier": "SS", "cat": "s165", "note": "赛娜开局", "code": "#蚊酱S16.5恭喜发财「赛娜开局」#MTA5OTk1MjMwNzcxNjIzNTQxNzg5MDExOTkwNDgw"},
  {"n": "阿兹尔开局", "ver": "V18.2", "tier": "SS", "cat": "s165", "note": "沙皇开局/恕瑞玛95", "code": "#蚊酱S16.5恭喜发财「阿兹尔开局」#MTA5OTk1MjMwNzcxNjIzNTQxNzg5MDEyMDY0MTk2"},
  {"n": "安妮开局", "ver": "V18.2", "tier": "SS", "cat": "s165", "note": "安妮开局/法师95", "code": "#蚊酱S16.5恭喜发财「安妮开局」#MTA5OTk1MjMwNzcxNjIzNTQxNzg5MDEyMTIyNjgw"},
  {"n": "奥恩开局", "ver": "V18.2", "tier": "S", "cat": "s165", "pending": true, "note": "奥恩开局可以搭配以上任意阵容玩，因为恭喜发财最不缺的就是装备", "code": ""}];

if (!window.LINEUP_DATA || !window.LINEUP_DATA.length) {
  console.error('LINEUP_DATA 加载失败');
}
//（注：内容由AI生成）
